name: test

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo $JSON | jq .
        env:
          JSON: ${{ toJSON(github) }}
